# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7b29ca3f22e8ac428be5c98dfcd7dc0c1a494de6d842f6ac56ce2f1310753947f379cc64427a3af0da4fdca9de441c047dd504648deb37a4aaab24fd335886d

test:
  secret_key_base: 21e027019f68abced42079583750b3afff4b1ec3241e0292eb3b34f9930ca91f1c434aa26c0cdef4a1101e8d91b981db86a8ef6cd6c8f7166c953e1a4a706582

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
